### ISSUE TITLE
deal with symlinks

### ISSUE THREAD

**Issue by lhirlimann** [3liz/qgis-plugin-manager#18]
```

root@VLIZ253F001:/srv/qgis/plugins# qgis-plugin-manager install cadastre
Installation cadastre latest
Traceback (most recent call last):
  File "/usr/local/bin/qgis-plugin-manager", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/qgis_plugin_manager/__main__.py", line 95, in main
    result = remote.install(*parameter)
  File "/usr/local/lib/python3.9/dist-packages/qgis_plugin_manager/remote.py", line 203, in install
    shutil.rmtree(existing)
  File "/usr/lib/python3.9/shutil.py", line 728, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib/python3.9/shutil.py", line 726, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
```
```
root@VLIZ253F001:/srv/qgis/plugins# ls -l
total 684
lrwxrwxrwx 1 root root     44 11 janv.  2021 atlasprint -> /srv/qgis-plugins/qgis-atlasprint/atlasprint
lrwxrwxrwx 1 root root     45 11 janv.  2021 cadastre -> /srv/qgis-plugins/QgisCadastrePlugin/cadastre
-rw-r--r-- 1 root root 691390 12 janv. 12:07 cadastre.1.13.5.zip
-rw-r--r-- 1 root root     55 12 janv. 12:05 sources.list
lrwxrwxrwx 1 root root     60 11 janv.  2021 wfsOutputExtension -> /srv/qgis-plugins/qgis-wfsOutputExtension/wfsOutputExtension
root@VLIZ253F001:/srv/qgis/plugins# 

```

**Comment by dmarteau** [comment]
This conflicts with the fact that install/upgrade always install in the specified directory: this means that links would be replaced by actual plugins directories wich may defeat  the purpose of using symbolic links.
