### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by katagen** [3liz/qgis-plugin-manager#19]
When I try to install the plugin, I have this error:

```
root@???? ~]# pip3 install qgis-plugin-manager
Collecting qgis-plugin-manager
  Using cached https://files.pythonhosted.org/packages/62/ec/4f26fb4effb3b306962b7a37eed735add070f26c5f7daea68bd1b3d0d0eb/qgis-plugin-manager-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-al40anxj/qgis-plugin-manager/setup.py", line 31, in <module>
        read_me = Path(__file__).parent.joinpath("README.md").read_text()
      File "/usr/lib/python3.6/pathlib.py", line 1197, in read_text
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2275: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-al40anxj/qgis-plugin-manager/
```

**Comment by Gustry** [comment]
Fixed with 399327e46deb7f5503fcec60fa1bfb4250ce6354 and 0.4.1 which has been released.
