### ISSUE TITLE
Error "no module pwd"

### ISSUE THREAD

**Issue by laurascasse** [3liz/qgis-plugin-manager#52]
I've installed the plugin manager on my server using OSGeo4W64 console.
But I have an error when i try to use the plugin 
What can I do ?

C:\Serveurs\OSGeo4W64\apps\qgis-ltr\python\plugins>qgis-plugin-manager list
Traceback (most recent call last):
  File "C:\Serveurs\OSGeo4W64\apps\Python37\Scripts\qgis-plugin-manager-script.py", line 11, in <module>
    load_entry_point('qgis-plugin-manager==1.4.1', 'console_scripts', 'qgis-plugin-manager')()
  File "C:\Serveurs\OSGeo4W64\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Serveurs\OSGeo4W64\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "C:\Serveurs\OSGeo4W64\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 2445, in load
    return self.resolve()
  File "C:\Serveurs\OSGeo4W64\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Serveurs\OSGeo4W64\apps\Python37\lib\site-packages\qgis_plugin_manager\__main__.py", line 14, in <module>
    from qgis_plugin_manager.local_directory import LocalDirectory
  File "C:\Serveurs\OSGeo4W64\apps\Python37\lib\site-packages\qgis_plugin_manager\local_directory.py", line 7, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

**Comment by Gustry** [comment]
Commit 88ee885396bbcc9bf59502df77aa8b8a5f3a2381
Please try with the newest version 1.4.2 of qgis-plugin-manager and reopen the ticket if necessary.

**Comment by Gustry** [comment]
This is not an error from QGIS-Plugin-Manager.
You need to setup your PYTHONPATH.

Otherwise you can skip this warning and continue. It's inviting you to do the `update` command.

It seems emoji is not supported on your terminal ?
